name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build
        run: |
          npm ci
          npm run build
          
      - name: Create .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Create .htaccess file
        run: |
          echo "AddType text/javascript .js" > dist/.htaccess
          echo "AddType text/javascript .mjs" >> dist/.htaccess
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist